### ISSUE TITLE
Make a PR

### ISSUE THREAD

**Issue by SomTambe** [SomTambe/Oktoberfest#1]
We need more contributors; contribute anything-code, links, etc.

**Comment by gitrahulgit** [comment]
I want to work on it!!

**Comment by heywassup123** [comment]
**I want to contribute to this issue, Please assign it to me @SomTambe**

**Comment by rspineda** [comment]
Hi, Yesterday night I sent a pull request. I added a new folder where I put an app about Local Storage on the browser so everyone can know how to storage information in the browser without using a external database. 
Greetings.

**Comment by SomTambe** [comment]
I will not be handling any external PRs. Kindly refrain from making any more pull requests.
